name: build_project
on:
 push:
  branches:
    - main
 workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019, ubuntu-18.04
    env:
      vcpkgDirectory: '${{ github.workspace }}/vcpkg'
    steps:
      - uses: lukka/get-cmake@latest
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
         fetch-depth: '2'   
