name: build_project
on:
 push:
  branches:
    - main
 workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    env:
      vcpkgDirectory: '${{ github.workspace }}/vcpkg'
    steps:
      - name: Setup Vcpkg
        uses: friendlyanon/setup-vcpkg@v1
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
         fetch-depth: '2'   
      
