name: build & test source
on:
 push:
 workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019]
        configuration: [Debug, Release]
        compiler: [clang]
    steps:
      - name: Install compiler
        id: install_cc
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: clang-latest
            
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
         fetch-depth: '2'   
         
      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master
        
      - name: Setup Vcpkg
        uses: friendlyanon/setup-vcpkg@v1
        with: { committish: 2cf957350da28ad032178a974607f59f961217d9 }
        
      - name: CMake Configure
        env:
            CC: ${{ steps.install_cc.outputs.cc }}
            CXX: ${{ steps.install_cc.outputs.cxx }}
        run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -G Ninja -D "CMAKE_TOOLCHAIN_FILE=${{env.VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake" -DCMAKE_BUILD_TYPE:STRING=${{ matrix.configuration }} -DCMAKE_CXX_COMPILER=${{env.CXX}} -DCMAKE_C_COMPILER=${{env.CC}}
      
      - name: CMake Build
        run: cmake --build ${{github.workspace}}/build

      - name: Unit Tests
        run: ctest --test-dir ${{github.workspace}}/build -VV
         
      
